############################# English ############################
[en]
languageName = "En"
title = "Quantmetrics"
contentDir = "content/english" # content/english
weight = 1
########### footer content ##########
footer_menu_left = "Menu"
footer_menu_middle = "Contact"
footer_menu_right = "Support"
footer_content = "Quantmetrics is providing<br>PK Modeling & Simulation services<br>to make your drug development a success."
# copyright
copyright = "Developed by [Quantmetrics](http://quantmetrics.org/) | All rights reserved 2021"



############################# Hebrew ############################
[he]
languageName = "He"
title = "Quantmetrics"
contentDir = "content/hebrew" # content/german
weight = 2
########### footer content ##########
footer_menu_left = "Firma"
footer_menu_middle = "Produkte"
footer_menu_right = "Support"
footer_content = "QUANTMETRICS נותן שירות "
# copyright
copyright = "Developed by [Quantmetrics](http://quantmetrics.org/) | All rights reserved 2021"