# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Services"
url = "pricing"
weight = 2

[[main]]
name = "About"
url = "blog"
weight = 3

[[main]]
name = "Contact"
url = "contact"
weight = 4

# footer menu left
[[footer_left]]
name = "About Us"
url = "blog"

[[footer_left]]
name = "Services"
url = "pricing"

[[footer_left]]
name = "Work with us"
url = "contact"

# footer menu middle
[[footer_middle]]
name = "Namir 68, Tel-Aviv, Israel"

[[footer_middle]]
name = "Email: info@quantmetrics.org"

[[footer_middle]]
name = "Phone: +972-54-888-6327"





