# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Services"
url = "pricing"
weight = 2

[[main]]
name = "About"
url = "blog"
weight = 3

[[main]]
name = "Contact"
url = "contact"
weight = 4

# footer menu left
[[footer_left]]
name = "About Us"
url = "#"

[[footer_left]]
name = "Quick Start"
url = "#"

[[footer_left]]
name = "Services"
url = "services"




