baseURL: http://quantmetrics.netlify.app
title: Quantmetrics
theme: bigspring-hugo-startup-theme
paginate: '3'
summaryLength: '15'
disqusShortname: ''
googleAnalytics: ''
markup:
  goldmark:
    renderer:
      unsafe: yes
